### ISSUE TITLE
路徑

### ISSUE THREAD

**Issue by ioritree** [smthemex/ComfyUI_Pops#1]
按照readme的路徑擺放設置

[Errno 2] No such file or directory: 'G:/AI/ComfyUI_windows_portable/ComfyUI/models/diffusers/models/texturing/learned_prior.pth
**>>>>必須從將models 從pOpsPaper\operators\搬移到diffusers目錄底**

Incorrect path_or_model_id: 'G:/AI/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI_Pops/weights/ip-adapter_sdxl.bin'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
**已經確認ip-adapter_sdxl.bin放在插件的weights跟目錄底**

下了這三組模型的需要文件一共74G,還是一如往常的大啊,

**Comment by smthemex** [comment]
在pOpsPaper/operators的repo栏，只需要填写G:/AI/ComfyUI_windows_portable/ComfyUI/models/diffusers，后面的那部分路径不需要填写，因为在代码里内置了指向models/texturing/learned_prior.pth 这几个模型的路径

**Comment by ioritree** [comment]
> G:/AI/ComfyUI_windows_portable/ComfyUI/models/diffusers
我懂你的意思,只是想說按照你的路徑必須是
G:\AI\ComfyUI_windows_portable\ComfyUI\models\diffusers\pOpsPaper\operators
而不是
G:\AI\ComfyUI_windows_portable\ComfyUI\models\diffusers

```
      ├──pOpsPaper/operators/models/
|             ├── instruct/
|                    ├── learned_prior.pth
|             ├── scene/
|                    ├── learned_prior.pth
|             ├── texturing/
|                    ├── learned_prior.pth
|             ├── union/
|                    ├── learned_prior.pth

```
-------------------------------
![QQ20240613144545](https://github.com/smthemex/ComfyUI_Pops/assets/46255792/a99ecd8b-3670-4e6d-9d16-31d82c6d633d)

**Incorrect path_or_model_id: 'G:/AI/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI_Pops/weights/ip-adapter_sdxl.bin'. Please provide either the path to a local folder or the repo_id of a model on the Hub.**

使用controlnet出現這個問題,已經確認ip-adapter_sdxl.bin已在插件的weights根目錄底
ip-adapter拉出來連不好嗎?ip-adapter 項目玩法非常多 ,綁死xl太可惜了

**Comment by smthemex** [comment]
你如果删掉这个，会自动从抱脸下一个。当然路径就不在这了。你可以尝试一下，我迟点改一下，把这个作为可选列表。

**Comment by smthemex** [comment]
这个BUG是系统调用的ip模块可能会被其他的已存在的其他ip模块干扰，比如其ip adapter PLUS，比如diffuse的ipadapter，我需要修改一下代码

**Comment by smthemex** [comment]
我尝试了其他几个IP的模型，发现向量的shape对不上，应该原代码的方法限制了，所以我本来加进去了，但是又删掉了。目前加了行指向IP的代码，看会不会引用出错。

**Comment by ioritree** [comment]
刪除了ip-adapter_sdxl.bin,讓hub自動下載完成後 ,又出現另外個錯誤

**Error occurred when executing Pops_Controlnet_Sampler:**

 has the config param `encoder_hid_dim_type` set to 'ip_image_proj' which requires the keyword argument `image_embeds` to be passed in  `added_conditions`

**Comment by smthemex** [comment]
这个多半是diffuer版本问题了，或者你选用的底模要改成jug试试。

**Comment by ioritree** [comment]
> 这个多半是diffuer版本问题了，或者你选用的底模要改成jug试试。

```
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

Total VRAM 24575 MB, total RAM 65469 MB
pytorch version: 2.1.0+cu121
xformers version: 0.0.22.post7
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
```

目前用的底模:juggernautXL_v9Rdphoto2Lightning
diffusers:0.26.2
transformers:4.41.2

------------------------

diffusers 更新至 0.29.0 就沒出錯了
